//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Networks.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Configured {
            get {
                return ((bool)(this["Configured"]));
            }
            set {
                this["Configured"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Водопроводы")]
        public string WaterPipeLayerName {
            get {
                return ((string)(this["WaterPipeLayerName"]));
            }
            set {
                this["WaterPipeLayerName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Канализации")]
        public string SewerLayerName {
            get {
                return ((string)(this["SewerLayerName"]));
            }
            set {
                this["SewerLayerName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Теплосети")]
        public string HeatingNetworkLayerName {
            get {
                return ((string)(this["HeatingNetworkLayerName"]));
            }
            set {
                this["HeatingNetworkLayerName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Линия_связи")]
        public string CommunicationCableLayerName {
            get {
                return ((string)(this["CommunicationCableLayerName"]));
            }
            set {
                this["CommunicationCableLayerName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Кабели низкого напряжения")]
        public string PowerCableLayerName {
            get {
                return ((string)(this["PowerCableLayerName"]));
            }
            set {
                this["PowerCableLayerName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AllowIntersection {
            get {
                return ((bool)(this["AllowIntersection"]));
            }
            set {
                this["AllowIntersection"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Газопроводы")]
        public string GasPipeLayerName {
            get {
                return ((string)(this["GasPipeLayerName"]));
            }
            set {
                this["GasPipeLayerName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Фундамент")]
        public string BuildingsFoundationLayerName {
            get {
                return ((string)(this["BuildingsFoundationLayerName"]));
            }
            set {
                this["BuildingsFoundationLayerName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Бортовой камень")]
        public string StreetSideStoneLayerName {
            get {
                return ((string)(this["StreetSideStoneLayerName"]));
            }
            set {
                this["StreetSideStoneLayerName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Наружная бровка")]
        public string ExternalEdgeLayerName {
            get {
                return ((string)(this["ExternalEdgeLayerName"]));
            }
            set {
                this["ExternalEdgeLayerName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Опора ВЛ до 1 кВ")]
        public string HvlSupportsFoundation1LayerName {
            get {
                return ((string)(this["HvlSupportsFoundation1LayerName"]));
            }
            set {
                this["HvlSupportsFoundation1LayerName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Опора ВЛ от 1кВ до 35 кВ")]
        public string HvlSupportsFoundation35LayerName {
            get {
                return ((string)(this["HvlSupportsFoundation35LayerName"]));
            }
            set {
                this["HvlSupportsFoundation35LayerName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Опора ВЛ от 35кВ")]
        public string HvlSupportsFoundationOverLayerName {
            get {
                return ((string)(this["HvlSupportsFoundationOverLayerName"]));
            }
            set {
                this["HvlSupportsFoundationOverLayerName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Красные линии")]
        public string RedLineLayerName {
            get {
                return ((string)(this["RedLineLayerName"]));
            }
            set {
                this["RedLineLayerName"] = value;
            }
        }
    }
}
